version: '2'
services:
  inz-app:
    image: edu.uz/inz:0.0.1-SNAPSHOT
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      - mongos
    environment:
      - READ_SOURCE=nosql

  postgresql:
    image: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_USER=postgres
     - POSTGRES_DB=inz

  mongos:
    image: mongo
    command: mongos --config /etc/mongos.yml --port 27017
    volumes:
     - './mongos.yml:/etc/mongos.yml'
    ports:
     - '27017:27017'

  mongo-config:
    image: mongo
    command: mongod --config /etc/mongo-config.yml --port 27018
    volumes:
     - './mongo-config.yml:/etc/mongo-config.yml'
    ports:
     - '27018:27018'

  mongo-shard-1:
    image: mongo
    command: mongod --config /etc/mongo-shard-1.yml --port 27021
    volumes:
     - './mongo-shard-1.yml:/etc/mongo-shard-1.yml'
    ports:
     - '27021:27021'

  mongo-shard-2:
    image: mongo
    command: mongod --config /etc/mongo-shard-2.yml --port 27022
    volumes:
     - './mongo-shard-2.yml:/etc/mongo-shard-2.yml'
    ports:
     - '27022:27022'

  mongo-shard-3:
    image: mongo
    command: mongod --config /etc/mongo-shard-3.yml --port 27023
    volumes:
     - './mongo-shard-3.yml:/etc/mongo-shard-3.yml'
    ports:
     - '27023:27023'
  mongo-shard-4:
    image: mongo
    command: mongod --config /etc/mongo-shard-4.yml --port 27024
    volumes:
     - './mongo-shard-4.yml:/etc/mongo-shard-4.yml'
    ports:
     - '27024:27024'
